version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgressql/data
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/app_db
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: {}